version: '3.8'
services:
  app:
    image: internos/iden3backend:latest
    volumes:
      - ./backend:/usr/src/myapp
      - ./backend/Settings.yaml:/usr/src/myapp/Settings.yaml
    environment:
      - DATABASE_URL=postgres://postgres:password@db/myapp
    depends_on:
      - db

  frontend:
    image: internos/iden3frontend:latest
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    environment:
      - BUILD_VERSION=0.2
    depends_on:
      - app

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myapp

volumes:
  postgres_data:
